### ISSUE TITLE
Identity is delivered through the browser, even in browser "incognito mode"

### ISSUE THREAD

**Issue by vielmetti** [tailscale-dev/id-headers-demo#2]
This is not a bug report, and I believe that all of the software involved
is doing exactly what it should be; nonetheless it's probably worth
noting somewhere.

If you run this demo in a Safari browser "private" window, or
a Chrome "incognito" window, on a machine that's connected
to Tailscale and is peering with the demo server, the demo server
will get your identity. I tired this initially to figure out how to get
past the short lag in DNS caching that connected me to the 
unauthenticated site initially.

This of course makes sense when you think that the auth is
coming from the network layer and not something stored
int he browser, but it's different enough from how incognito 
breaks the usual auth setup that it's worth thinking about.

**Comment by thisisparker** [comment]
This is a good point and I've opened a PR adding it to the README here. I also noted that it will even work across devices. I think that can be a real strength to this model if you know to expect it, but I agree it might be a surprise if you don't!
